version: '3.8'

x-service-basic: &service-basic
  environment:
    POSTGRES_DB: abac_db
    POSTGRES_USER: abac_user
    POSTGRES_PASSWORD: abac_password
    POSTGRES_URL: "postgres://abac_user:abac_password@db/abac_db?sslmode=disable"

services:
  server:
    build:
        context: ./
        dockerfile: ./app/build/docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    <<: *service-basic

  db:
    image: postgres:13.2-alpine
    <<: *service-basic
