version: '3.8'

services:
  web:
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080

  db:
    image: postgres:13.2-alpine
    environment:
      DB_NAME: abac_db
      DB_USERNAME: abac_user
      DB_PASSWORD: abac_password
