version: '3.8'

services:
  web:
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: abac_db
      POSTGRES_USER: abac_user
      POSTGRES_PASSWORD: abac_password
